"""Add paid_by_user_id to bills

Revision ID: 34d9385deadc
Revises: 74633d9f64d2
Create Date: 2026-03-17 00:25:03.898642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34d9385deadc'
down_revision: Union[str, Sequence[str], None] = '74633d9f64d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('paid_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bills', 'users', ['paid_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bills', type_='foreignkey')
    op.drop_column('bills', 'paid_by_user_id')
    # ### end Alembic commands ###
