"""Add textract usage and group currency

Revision ID: 74633d9f64d2
Revises: bcb497c6c8f3
Create Date: 2026-03-17 00:05:15.862643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74633d9f64d2'
down_revision: Union[str, Sequence[str], None] = 'bcb497c6c8f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('users', sa.Column('textract_usage_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'textract_usage_count')
    op.drop_column('groups', 'currency')
    # ### end Alembic commands ###
