"""add removed_at to group_member

Revision ID: e6682ff8d0f6
Revises: b94e48ac6462
Create Date: 2026-03-29 12:35:41.896670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6682ff8d0f6'
down_revision: Union[str, Sequence[str], None] = 'b94e48ac6462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_members', sa.Column('removed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_members', 'removed_at')
    # ### end Alembic commands ###
